welcome:
  enabled: true
  title: "<gold>Server <aqua>Name"
  subtitle: "<gray>Welcome <white>%player_name%</white>!"
  message: |
    <green>Welcome back to the server, <white>%player_name%!
    <gold>• <yellow>Use <gold>/home <yellow>to return to your base.
    <gold>• <yellow>Use <gold>/claim <yellow>to protect a new territory.
    <gold>• <yellow>Join our <gold>Discord <yellow>to report any issues!
    <aqua>[NOTICE] <white>This server may have players recording or streaming.
    <gray>Please avoid sharing personal info or using inappropriate language.

hud:
  actionbar:
    enabled: true
    message: "Next restart at <gray>%swissknife_restarttime_formated%"
  bossbar:
    enabled: true
    message: "<gray>Player: <white>%player_name% <red>❤ %player_health_rounded%"
    hide-during-raids: true
    hide-near-bosses: true
  compass:
    enabled: true
    north: "N"
    south: "S"
    east: "E"
    west: "W"
    divider: "  -  -  |  -  -  "
    waypoints:
      death:
        enabled: true
        icon: "☠"
        color: "<white>"
        despawn-time: 1800
        messages:
          death: "#I <yellow>%player_name% died at location <white>#X #Y #Z (#W)."
          near: "<yellow>You are close to your items!"
      waypoint:
        enabled: true
        icon: "V"
        note: "TODO"
      spawn:
        enabled: true
        icon: "#"
        node: "TODO"

restart:
  enabled: true
  schedules:
    - "3:00"
    - "12:00"
    - "18:19"
  alerts: [1800, 600, 60, 30, 10, 3, 2, 1]
  messages:
    minutes: "<yellow>The server will restart in <white># <yellow>minutes!"
    minute: "<yellow>The server will restart in <white># <yellow>minute!"
    seconds: "<yellow>The server will restart in <white># <yellow>seconds!"
    second: "<yellow>The server will restart in <white># <yellow>second!"
    restarting: "<red>Restarting now..."